[workspace]
members = [
    "crates/rustlycss_types",
    "crates/rustlycss_parser",
    "crates/rustlycss_codegen",
    "crates/rustlycss_nested",
    "crates/rustlycss_simple_vars",
    "crates/playground",
]